apiVersion: v1
kind: Service
metadata:
  name: ztm-ca
  labels:
    app: ztm-ca
spec:
  type: LoadBalancer
  selector:
    app: ztm-ca
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: ztm-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ztm-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ztm-ca
  template:
    metadata:
      labels:
        app: ztm-ca
    spec:
      containers:
        - name: ztm-ca
          image: flomesh/ztm:0.0.4
          ports:
            - containerPort: 9999
          command: [ 'ztm' ]
          args: [
            "run",
            "ca",
            "--listen",
            "0.0.0.0:9999",
            "--database",
            "ztm.db",
          ]