apiVersion: v1
kind: Service
metadata:
  name: global-egress-gateway
  namespace: egress-gateway
  labels:
    app: global-egress-gateway
  annotations:
    openservicemesh.io/egress-gateway-mode: sock5
spec:
  ports:
    - port: 1080
      name: pipy-socks-port
      appProtocol: tcp
  selector:
    app: global-egress-gateway
    mode: sock5