#kind: Service
#apiVersion: v1
#metadata:
#  name: order-service
#spec:
#  selector:
#    app: order-service
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 9000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service
      containers:
        - name: order-service
          image: cybwan/spring-consul-demo:order-service
          ports:
            - containerPort: 9000