kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
nodes:
  - role: control-plane
    image: kindest/node:v1.20.15
    extraPortMappings:
      - containerPort: 80
        hostPort: 8091
        protocol: TCP
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6446